baseURL = 'https://ansulev.com'
languageCode = 'es'
defaultContentLanguage = 'es'
title = 'Angel Georgiev Sulev | Ciberseguridad + IA Agéntica'

# Configuración multiidioma
[languages]
  [languages.es]
    languageName = 'Español'
    weight = 1
    title = 'Angel Georgiev Sulev | Ciberseguridad + IA Agéntica'
    [languages.es.params]
      description = 'Especialista senior ciberseguridad e IA Agéntica. 30+ años transformando seguridad en ventaja competitiva.'
  
  [languages.en]
    languageName = 'English'
    weight = 2
    title = 'Angel Georgiev Sulev | Cybersecurity + Agentic AI'
    [languages.en.params]
      description = 'Senior cybersecurity specialist + Agentic AI. 30+ years transforming security into competitive advantage.'

# Parámetros globales
[params]
  author = 'Angel Georgiev Sulev'
  description = 'Especialista senior en ciberseguridad e IA Agéntica con 30+ años de experiencia'
  keywords = ['ciberseguridad', 'IA agéntica', 'custom LLMs', 'MLSecOps', 'fine-tuning', 'ICS/OT security']
  
  # Información de contacto
  email = 'angel.sulev@gmail.com'
  phone = '+34 633 600 515'
  location = 'Lleida, España'
  
  # Redes sociales
  [params.social]
    linkedin = 'https://linkedin.com/in/ansulev'
    github = 'https://github.com/ansulev'
    twitter = 'https://twitter.com/ansulev'
  
  # Analytics (configurar después)
  googleAnalytics = ''

# Menú de navegación
[[menu.main]]
  name = 'Inicio'
  url = '/'
  weight = 10

[[menu.main]]
  name = 'Sobre Mí'
  url = '/sobre-mi/'
  weight = 20

[[menu.main]]
  name = 'Servicios'
  url = '/servicios/'
  weight = 30

[[menu.main]]
  name = 'Proyectos'
  url = '/proyectos/'
  weight = 40

[[menu.main]]
  name = 'Blog'
  url = '/blog/'
  weight = 50

[[menu.main]]
  name = 'Contacto'
  url = '/contacto/'
  weight = 60

# Configuración de markup y SEO
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'github'
    lineNos = true

# Sitemap
[sitemap]
  changefreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

# Outputs
[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML']
  section = ['HTML', 'RSS']
  taxonomy = ['HTML', 'RSS']
  term = ['HTML', 'RSS']

# Configuración de construcción
[build]
  writeStats = true

# Minificación
[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDefaultAttrVals = false
      keepDocumentWhitespace = false
      keepEndTags = true
      keepQuotes = false

