# Configuración básica del sitio
baseURL = 'https://ansulev.com'
languageCode = 'es'
title = 'Angel Georgiev Sulev | Ciberseguridad + IA Agéntica'

# Configuración de markup
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

ignoreLogs = ['warning-goldmark-raw-html']

# Información personal y contacto
[params]
author = 'Angel Georgiev Sulev'
email = 'angel@ansulev.com'
phone = '+34 624 676 696'
location = 'Barcelona, España'
description = 'Especialista senior ciberseguridad e IA Agéntica. 30+ años transformando seguridad en ventaja competitiva.'

# Redes sociales
[social]
  linkedin = 'https://linkedin.com/in/angelsulev'
  github = 'https://github.com/ansulev'
  twitter = 'https://twitter.com/ansulev'

# Menú de navegación
[[menu.main]]
  name = 'Inicio'
  url = '/'
  weight = 10

[[menu.main]]
  name = 'Sobre Mí'
  url = '/sobre-mi/'
  weight = 20

[[menu.main]]
  name = 'Servicios'
  url = '/servicios/'
  weight = 30

[[menu.main]]
  name = 'Proyectos'
  url = '/proyectos/'
  weight = 40

[[menu.main]]
  name = 'Blog'
  url = '/blog/'
  weight = 50

[[menu.main]]
  name = 'Contacto'
  url = '/contacto/'
  weight = 60
