# Configuración básica del sitio
baseURL = 'https://ansulev.com'
languageCode = 'es'
defaultContentLanguage = 'es'
title = 'Angel Georgiev Sulev | Ciberseguridad + IA Agéntica'

# Configuración multiidioma
[languages]
  [languages.es]
    languageName = 'Español'
    weight = 1
    title = 'Angel Georgiev Sulev | Ciberseguridad + IA Agéntica'
    languageCode = 'es'
    [languages.es.params]
      description = 'Especialista senior ciberseguridad e IA Agéntica. 30+ años transformando seguridad en ventaja competitiva.'

  [languages.en]
    languageName = 'English'
    weight = 2
    title = 'Angel Georgiev Sulev | Cybersecurity + Agentic AI'
    languageCode = 'en'
    [languages.en.params]
      description = 'Senior cybersecurity specialist + Agentic AI. 30+ years transforming security into competitive advantage.'

  [languages.ca]
    languageName = 'Català'
    weight = 3
    title = 'Angel Georgiev Sulev | Ciberseguretat + IA Agèntica'
    languageCode = 'ca'
    [languages.ca.params]
      description = 'Especialista senior en ciberseguretat i IA Agèntica. 30+ anys transformant seguretat en avantatge competitiu.'

# Menú de navegación
[[menu.main]]
  name = 'Inicio'
  url = '/'
  weight = 10

[[menu.main]]
  name = 'Sobre Mí'
  url = '/sobre-mi/'
  weight = 20

[[menu.main]]
  name = 'Servicios'
  url = '/servicios/'
  weight = 30

[[menu.main]]
  name = 'Proyectos'
  url = '/proyectos/'
  weight = 40

[[menu.main]]
  name = 'Blog'
  url = '/blog/'
  weight = 50

[[menu.main]]
  name = 'Contacto'
  url = '/contacto/'
  weight = 60
