name: Deploy Hugo site to Kinsta

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Check public directory
        run: |
          echo "Checking if public directory exists..."
          ls -la public/
          echo "Public directory contents:"
          ls -la public/ | head -10

      - name: Deploy to Kinsta
        uses: kinsta/actions@main
        with:
          site_id: ${{ secrets.KINSTA_SITE_ID }}
          api_key: ${{ secrets.KINSTA_API_KEY }}
          build_dir: public/
